---
title: Blog Post 6
author: Package Build
date: '2024-10-12'
slug: blog-post-7
categories: []
tags: []
---
#Victor Bowker
#Week 6
Almost there

```{r, echo=FALSE, warning = FALSE, message = FALSE}
library(car)
library(caret)
library(cowplot)
library(curl)
library(CVXR)
library(foreign)
library(geofacet)
library(glmnet)
library(haven)
library(janitor)
library(kableExtra)
library(maps)
library(mlr3)
library(randomForest)
library(ranger)
library(RColorBrewer)
library(rstan)
library(scales)
library(sf)
library(shinystan)
library(tidyverse)
library(viridis)
```

```{r, echo=FALSE, warning = FALSE, message = FALSE}
# Read popular vote datasets. 
d_popvote <- read_csv("popvote_1948_2020.csv")
d_state_popvote <- read_csv("state_popvote_1948_2020.csv")
```
```{r, echo=FALSE, warning = FALSE, message = FALSE}
# Read elector distribution dataset. 
d_ec <- read_csv("corrected_ec_1948_2024.csv")
```
```{r, echo=FALSE, warning = FALSE, message = FALSE}
# Read ads datasets. 
ad_campaigns <- read_csv("ad_campaigns_2000-2012.csv")
ad_creative <- read_csv("ad_creative_2000-2012.csv")
ads_2020 <- read_csv("ads_2020.csv")
facebook_ads_2020 <- read_csv("facebook_ads_2020.csv")
facebook_ads_biden_2020 <- read_csv("facebook_ads_biden_2020.csv")
campaign_spending <- read_csv("FEC_contributions_by_state_2008_2024.csv")
```
```{r, echo=FALSE, warning = FALSE, message = FALSE}
# Read polling data. 
d_polls <- read_csv("national_polls_1968-2024.csv")
d_state_polls <- read_csv("state_polls_1968-2024.csv")
```
```{r, echo=FALSE, warning = FALSE, message = FALSE}
# Read turnout data. 
d_turnout <- read_csv("state_turnout_1980_2022.csv")
```

```{r, echo=FALSE, warning = FALSE, message = FALSE}
# Tone and Political Ads. 
ad_campaigns |>
  left_join(ad_creative) |>
  group_by(cycle, party) |> mutate(tot_n=n()) |> ungroup() |>
  group_by(cycle, party, ad_tone) |> summarise(pct=n()*100/first(tot_n)) |>
  filter(!is.na(ad_tone)) |>
  ggplot(aes(x = cycle, y = pct, fill = ad_tone, group = party)) +
  geom_bar(stat = "identity") +
  scale_x_continuous(breaks = seq(2000, 2012, 4)) +
  ggtitle("Campaign Ads Aired By Tone") +
  scale_fill_manual(values = c("red","orange","gray","darkgreen","white"), name = "tone") +
  xlab("") + ylab("%") +
  facet_wrap(~ party) + theme_minimal() +
  theme(axis.title = element_text(size=20),
        axis.text = element_text(size=15),
        strip.text.x = element_text(size = 20))
```
```{r, echo=FALSE, warning = FALSE, message = FALSE}
## The Purpose of Political Ads
ad_campaigns |>
  left_join(ad_creative) |>
  group_by(cycle, party) |> mutate(tot_n=n()) |> ungroup() |>
  group_by(cycle, party, ad_purpose) |> summarise(pct=n()*100/first(tot_n)) |>
  filter(!is.na(ad_purpose)) |>
  bind_rows( ##2016 raw data not public yet! This was entered manually
    data.frame(cycle = 2016, ad_purpose = "personal", party = "democrat", pct = 67),
    data.frame(cycle = 2016, ad_purpose = "policy", party = "democrat", pct = 12),
    data.frame(cycle = 2016, ad_purpose = "both", party = "democrat", pct = 21),
    data.frame(cycle = 2016, ad_purpose = "personal", party = "republican", pct = 11),
    data.frame(cycle = 2016, ad_purpose = "policy", party = "republican", pct = 71),
    data.frame(cycle = 2016, ad_purpose = "both", party = "republican", pct = 18)
  ) |>
  ggplot(aes(x = cycle, y = pct, fill = ad_purpose, group = party)) +
  geom_bar(stat = "identity") +
  scale_x_continuous(breaks = seq(2000, 2016, 4)) +
  # ggtitle("Campaign Ads Aired By Purpose") +
  scale_fill_manual(values = c("grey","red","darkgreen","black","white"), name = "purpose") +
  xlab("") + ylab("%") +
  facet_wrap(~ party) + theme_minimal() +
  theme(axis.title = element_text(size=20),
        axis.text = element_text(size=15),
        strip.text.x = element_text(size = 20))
```
```{r, echo=FALSE, warning = FALSE, message = FALSE}
## The Elections and Their Issues
top_issues <- ad_campaigns |> 
  left_join(ad_creative) |>
  filter(!grepl("None|Other", ad_issue)) |>
  group_by(cycle, ad_issue) |> summarise(n=n()) |> top_n(5, n)
```
```{r, echo=FALSE, warning = FALSE, message = FALSE}
### making each plot in a grid to have its own x-axis (issue name)
### is tricky with `facet_wrap`, so we use this package `cowplot`
### which allows us to take a list of separate plots and grid them together
plist <- lapply(c(2000,2004,2008,2012), function(c) {
  top_issues |> filter(cycle == c) |> 
    ggplot(aes(x = reorder(ad_issue, n), y = n)) +
    geom_bar(stat = "identity") + coord_flip() + theme_bw() +
    xlab("") + ylab("number ads aired") + ggtitle(paste("Top 5 Ad\nIssues in",c))
  
})
cowplot::plot_grid(plotlist = plist, nrow = 2, ncol = 2, align = "hv")
```
```{r, echo=FALSE, warning = FALSE, message = FALSE}
## Campaign Ads Aired By Issue and Party: 2000
party_issues2000 <- ad_campaigns |>
  filter(cycle == 2000) |>
  left_join(ad_creative) |>
  filter(ad_issue != "None") |>
  ## this `group_by` is to get our denominator
  group_by(ad_issue) |> mutate(tot_n=n()) |> ungroup() |>
  ## this one is get numerator and calculate % by party
  group_by(ad_issue, party) |> summarise(p_n=n()*100/first(tot_n)) |> ungroup() |>
  ## finally, this one so we can sort the issue names
  ## by D% of issue ad-share instead of alphabetically
  group_by(ad_issue) |> mutate(Dp_n = ifelse(first(party) == "democrat", first(p_n), 0))

ggplot(party_issues2000, aes(x = reorder(ad_issue, Dp_n), y = p_n, fill = party)) + 
  geom_bar(stat = "identity") +
  scale_fill_manual(values = c("blue", "red")) +
  ylab("% of ads on topic from each party") + xlab("issue") + 
  # ggtitle("Campaign Ads Aired by Topic in 2000") +
  coord_flip() + 
  theme_bw()
```
```{r, echo=FALSE, warning = FALSE, message = FALSE}
## Campaign Ads Aired By Issue and Party: 2012
party_issues2012 <- ad_campaigns |>
  filter(cycle == 2012) |>
  left_join(ad_creative) |>
  filter(ad_issue != "None") |>
  group_by(cycle, ad_issue) |> mutate(tot_n=n()) |> ungroup() |>
  group_by(cycle, ad_issue, party) |> summarise(p_n=n()*100/first(tot_n)) |> ungroup() |>
  group_by(cycle, ad_issue) |> mutate(Dp_n = ifelse(first(party) == "democrat", first(p_n), 0))

ggplot(party_issues2012, aes(x = reorder(ad_issue, Dp_n), y = p_n, fill = party)) + 
  geom_bar(stat = "identity") +
  scale_fill_manual(values = c("blue", "red")) +
  ylab("% of ads on topic from each party") + xlab("issue") +
  # ggtitle("Campaign Ads Aired by Topic in 2012") +
  coord_flip() + 
  theme_bw()
```
```{r, echo=FALSE, warning = FALSE, message = FALSE}
## When to Buy Ads? 
ad_campaigns |>
  mutate(year = as.numeric(substr(air_date, 1, 4))) |>
  mutate(month = as.numeric(substr(air_date, 6, 7))) |>
  filter(year %in% c(2000, 2004, 2008, 2012), month > 7) |>
  group_by(cycle, air_date, party) |>
  summarise(total_cost = sum(total_cost)) |>
  ggplot(aes(x=air_date, y=total_cost, color=party)) +
  # scale_x_date(date_labels = "%b, %Y") +
  scale_y_continuous(labels = dollar_format()) +
  scale_color_manual(values = c("blue","red"), name = "") +
  geom_line() + geom_point(size=0.5) +
  facet_wrap(cycle ~ ., scales="free") +
  xlab("") + ylab("ad spend") +
  theme_bw() +
  theme(axis.title = element_text(size=20),
        axis.text = element_text(size=11),
        strip.text.x = element_text(size = 20))
```
```{r, echo=FALSE, warning = FALSE, message = FALSE}
## Tone in Political Ads
ad_campaigns |>
  left_join(ad_creative) |>
  filter(ad_tone %in% c("attack", "promote")) |>
  mutate(year = as.numeric(substr(air_date, 1, 4))) |>
  mutate(month = as.numeric(substr(air_date, 6, 7))) |>
  filter(year %in% c(2000, 2004, 2008, 2012), month > 7) |>
  group_by(cycle, air_date, ad_tone) |>
  summarise(total_cost = sum(n_stations)) |>
  group_by(cycle, air_date) |>
  mutate(total_cost = total_cost/sum(total_cost)) |>
  ungroup() |>
  ggplot(aes(x=air_date, y=total_cost, fill=ad_tone, color=ad_tone)) +
  # scale_x_date(date_labels = "%b") +
  scale_fill_manual(values = c("purple","green"), name = "ad tone") +
  scale_color_manual(values = c("purple","green"), name = "ad tone") +
  geom_bar(stat = "identity") +
  facet_wrap(cycle ~ ., scales="free") +
  xlab("") + ylab("% of ads bought on day") +
  theme_bw() +
  theme(axis.title = element_text(size=20),
        axis.text = element_text(size=10),
        strip.text.x = element_text(size = 20))
```
```{r, echo=FALSE, warning = FALSE, message = FALSE}
## The State-level Air War in 2008 (Obama vs. McCain)
ad_campaigns |>
  mutate(year = as.numeric(substr(air_date, 1, 4))) |>
  mutate(month = as.numeric(substr(air_date, 6, 7))) |>
  mutate(state = state.name[match(state, state.abb)]) |>
  filter(cycle == 2008) |>
  left_join(d_state_popvote |> filter(year == 2008) |> select(-year), by="state") |>
  mutate(winner=ifelse(D_pv2p > R_pv2p, "democrat", "republican")) |>
  group_by(cycle, state, air_date, party, winner) |>
  summarise(total_cost = sum(total_cost)) |>
  filter(!is.na(state)) |>
  # ggplot(aes(x=air_date, y=log(total_cost+1), color=party)) +
  ggplot(aes(x=party, y=total_cost, fill=party)) +
  geom_bar(stat="identity") +
  geom_rect(aes(fill=winner), xmin=-Inf, xmax=Inf, ymin=46.3*10^6, ymax=52*10^6) +
  facet_geo(~ state, scales="free_x") +
  scale_fill_manual(values = c("blue", "red")) +
  scale_y_continuous(labels = unit_format(unit = "M", scale = 1e-6)) +
  xlab("") + ylab("ad spend") +
  theme_bw() +
  theme(axis.title.x=element_blank(), 
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())

```
```{r, echo=FALSE, warning = FALSE, message = FALSE}
# Visualizing Facebook ads and Biden Facebook ads in 2020. 
d_facebook <- facebook_ads_2020 |> 
  rename(date = from_date, new_ads = num_of_new_ads) |> 
  group_by(date) |> 
  summarize(new_spend = sum(new_spend, na.rm = T),
            new_ads = sum(new_ads, na.rm = T))

d_facebook |> 
  ggplot(aes(x = date, y = new_ads)) + 
  geom_line() +
  geom_smooth(method = "lm", se = TRUE) +
  labs(x = "Date", 
       y = "New Facebook Ads") +
  theme_minimal()

d_facebook |> 
  ggplot(aes(x = date, y = new_spend)) +
  geom_line() +
  scale_y_continuous(labels = dollar_format()) +
  geom_smooth(method = "lm", se = TRUE) + 
  labs(x = "Date", 
       y = "New Facebook Ad Spending") +
  theme_minimal()
  
d_facebook_biden <- facebook_ads_biden_2020 |> 
  rename(date = from_date, new_ads = num_of_new_ads) |> 
  group_by(date) |> 
  summarize(new_spend = sum(new_spend, na.rm = T),
            new_ads = sum(new_ads, na.rm = T))

d_facebook_biden |>
  ggplot(aes(x = date, y = new_ads)) + 
  geom_line() +
  geom_smooth(method = "lm", se = TRUE) +
  labs(x = "Date", 
       y = "New Facebook Ads (Biden Only)") +
  theme_minimal()

d_facebook_biden |>
  ggplot(aes(x = date, y = new_spend)) +
  geom_line() +
  scale_y_continuous(labels = dollar_format()) +
  geom_smooth(method = "lm", se = TRUE) + 
  labs(x = "Date", 
       y = "New Facebook Ad Spending (Biden Only)")
  theme_minimal()
```







