---
title: Post-Election Campaign Narrative
author: Victor Bowker
date: '2024-12-08'
slug: post-election-campaign-narrative
categories: []
tags: []
---

# Welcome Back!

We are nearing the end of the semester, and that means this blog as well! I am excited to be completing this blog by talking about my home state, **Massachusetts**! I will briefly discuss an overview of the Bay State, including demography and geography, then I will explain how the election was forcasted in Massachusetts, and finally I will compare the projection to the true results!

## Brief Overview: Massachusetts

Located in the North East of these United States, Massachusetts was the a hot spot in early colonial happenings. The Plymouth Colony was founded by the Pilgrims back in 1620, and the state became the Mass Bay Colony in 1930! Later, Massachusetts was an incredibly important location during Revolutionary War efforts, including the Boston Tea Party, Boston Massacre, and Battle of Lexington and Concord!

As for present day, Massachusetts is home to 7 million people, making it the most populated state in all of New England. Massachusetts is represented on the national stage by two Senators (Warren & Markey), as well as 9 members of the House of Representatives (Neal, McGovern, Trahan, Auchincloss, Clark, Moulton, Pressley, Lynch, Keating).

According to the US Census in 2020, 61.6% of Mass. residents are white only, while 12.4% are black only, 18.7% is Hispanic, and 6% is Asian. Boston is the most populated city, followed by Worcester and Springfield.

In past elections, Massachusetts has been a solid blue state, though it has voted for Republicans 4 times in the last 100 years, twice for Eisenhower and twice for Reagan. Interestingly, of Massachusetts' last 7 Governors, 5 have been Republican.

## What Forecasters Believed

In 1,000 forecast simulations, FiveThirtyEight had Harris winning 1,000 times, so its safe to say Massachusetts was not at top of mind. In 2016, President Trump received only 32.8% of the Massachusetts Popular Vote. In 2020, he received even less, with only 32.1%. Massachusetts is *so* liberal that FiveThirtyEight even said California was more likely to flip for Trump than the Bay State.

In 2024, President Trump made relative headway in Mass, seizing 36.5% of the vote! Vice President Harris clearly took the 11 Electoral Votes with 61.3% of the Popular Vote, but President Trump gained a small bit of ground. My forecast also gave Harris a healthy, nay outright, lead in my home state.

## Campaign Evaluation

As of late September, President Trump did not hold a single campaign event in Massachusetts. Vice President Elect Vance did in fact speak at one single event, the International Association of Fire Fighters Convention, though it did not do much to sway the vote. In his first campaign, President Trump did hold two events, one in Worcester, and another in Lowell.

On the other hand, Vice President Harris held an event in Pittsfield, and Minnesota Governor Tim Walz visited Mass twice. Harris used these events as fundraisers, leaning into her strong blue donor base. There were also campaign sightings in Provincetown, the small town at the tip of Cape Cod.

It seems that Trump and his campaign was incredibly aware of Massachusetts' past voting history, and made no effort to sway the election this time around. Harris made some speeches, likely just to raise a couple million dollars to continue funding her incredibly expensive campaign. There would be no reason to judge Trump for not hitting the Bay State in his campaign, as it clearly would have been a waste of time and money—some things will (probably) never change.

There were nearly no deviations from the projections. This isn't a surprise!

## Source

<https://www.google.com/search?client=safari&rls=en&q=mass+history&ie=UTF-8&oe=UTF-8>

<https://www.census.gov/quickfacts/fact/table/MA/PST045223>

<https://projects.fivethirtyeight.com/polls/>

<https://www.telegram.com/story/news/politics/2024/09/06/donald-trump-kamala-harris-presidential-race-jd-vance-tim-walz-massachusetts-new-england-campaign/75075122007/>
